# Generated by Django 3.2.19 on 2023-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230521_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
