# Generated by Django 3.2.19 on 2023-05-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_table_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
